import type {
  TechStackAssessment,
  ArchitectureDecision,
  RoadmapItem,
  TeamHealthMetric,
  EngineeringMetric,
} from "./types";

// ─── 12 Architecture Decision Records ─────────────────────────────────────────

export const demoADRs: ArchitectureDecision[] = [
  {
    id: "ADR-001",
    title: "Adopt Next.js for web platform",
    status: "accepted",
    date: "2025-11-03",
    impact: "high",
    context: "Team split between React SPA and full-stack framework. Need SSR for SEO and unified deployment model.",
    decision: "Standardize on Next.js 15 with App Router for all new web applications.",
    consequences: "Single framework reduces context switching. Server components reduce client bundle. Migration of legacy SPAs will take 2 quarters.",
    supersededBy: null,
  },
  {
    id: "ADR-002",
    title: "PostgreSQL as primary data store",
    status: "accepted",
    date: "2025-11-10",
    impact: "high",
    context: "Current mix of MySQL and MongoDB creates operational burden. Need ACID compliance and rich querying.",
    decision: "Consolidate on PostgreSQL 16 with Supabase for managed hosting and row-level security.",
    consequences: "Simplified ops, strong consistency. MongoDB workloads require migration scripts. JSONB covers document use cases.",
    supersededBy: null,
  },
  {
    id: "ADR-003",
    title: "Introduce event-driven architecture with RabbitMQ",
    status: "proposed",
    date: "2026-05-22",
    impact: "high",
    context: "Monolith coupling slowing down teams. Order processing and notification systems need decoupling.",
    decision: "Introduce RabbitMQ for async messaging between bounded contexts. Start with order-to-fulfillment pipeline.",
    consequences: "Improved team autonomy. Requires operational investment in message broker monitoring and dead-letter handling.",
    supersededBy: null,
  },
  {
    id: "ADR-004",
    title: "Migrate CI/CD from Jenkins to GitHub Actions",
    status: "accepted",
    date: "2026-01-15",
    impact: "medium",
    context: "Jenkins maintenance overhead high. Team already on GitHub. Need simpler pipeline management.",
    decision: "Migrate all CI/CD pipelines to GitHub Actions with reusable workflows.",
    consequences: "Reduced infra maintenance burden. Lost some legacy Jenkins plugin integrations — rebuilt as custom actions.",
    supersededBy: null,
  },
  {
    id: "ADR-005",
    title: "Adopt TypeScript across all services",
    status: "accepted",
    date: "2025-12-01",
    impact: "high",
    context: "JavaScript services accumulating runtime type errors. Onboarding friction for new engineers.",
    decision: "All new services and significant refactors must use TypeScript with strict mode enabled.",
    consequences: "Defect rate dropped 30% in frontend team. Legacy JS services grandfathered with migration backlog tickets.",
    supersededBy: null,
  },
  {
    id: "ADR-006",
    title: "Use Vercel for frontend hosting",
    status: "accepted",
    date: "2026-02-10",
    impact: "medium",
    context: "Current AWS CloudFront + S3 setup requires manual cache invalidation. Preview deployments missing.",
    decision: "Host all Next.js applications on Vercel Pro tier with automatic preview deployments per PR.",
    consequences: "Deploy previews accelerated review cycles. Lock-in mitigated by standard Next.js output.",
    supersededBy: null,
  },
  {
    id: "ADR-007",
    title: "Centralized logging with OpenTelemetry",
    status: "proposed",
    date: "2026-06-01",
    impact: "medium",
    context: "Debugging distributed failures requires correlating logs across 6+ services. No unified trace ID.",
    decision: "Instrument all services with OpenTelemetry SDKs. Export traces to Honeycomb and logs to Grafana Loki.",
    consequences: "Observability vastly improved. Instrumentation effort estimated at 4 sprints across all teams.",
    supersededBy: null,
  },
  {
    id: "ADR-008",
    title: "Feature flags via LaunchDarkly",
    status: "accepted",
    date: "2026-03-14",
    impact: "medium",
    context: "Long-running feature branches cause merge hell. Need safer continuous delivery patterns.",
    decision: "Adopt LaunchDarkly for feature flagging. Trunk-based development with flags gating incomplete features.",
    consequences: "Deployment frequency up 2x. Flag debt requires quarterly cleanup sprints.",
    supersededBy: null,
  },
  {
    id: "ADR-009",
    title: "Monorepo with Turborepo",
    status: "superseded",
    date: "2025-06-20",
    impact: "high",
    context: "Multiple repos causing duplicated config and inconsistent tooling across 8 TypeScript packages.",
    decision: "Consolidate into a single monorepo managed by Turborepo with shared ESLint, TSConfig, and build pipelines.",
    consequences: "Build caching reduced CI times 60%. IntelliSense improved. Some teams resisted monorepo workflow initially.",
    supersededBy: "ADR-012",
  },
  {
    id: "ADR-010",
    title: "Deprecate GraphQL in favor of tRPC",
    status: "deprecated",
    date: "2025-04-08",
    impact: "high",
    context: "GraphQL schema maintenance burdens 3-person API team. Internal services don't need public-facing query language.",
    decision: "Replace GraphQL with tRPC for internal service-to-service and BFF communication.",
    consequences: "Type safety end-to-end eliminated an entire class of runtime errors. External API still uses REST.",
    supersededBy: null,
  },
  {
    id: "ADR-011",
    title: "Redis for session and cache layer",
    status: "accepted",
    date: "2026-04-01",
    impact: "low",
    context: "In-memory session stores cause sticky-session requirement on load balancer. Rate limiting needs shared state.",
    decision: "Deploy Redis Cluster for distributed session storage, rate limiting counters, and query result caching.",
    consequences: "Stateless app servers enable horizontal scaling. Added ~$400/month in managed Redis costs.",
    supersededBy: null,
  },
  {
    id: "ADR-012",
    title: "Turborepo → Nx migration for polyglot support",
    status: "proposed",
    date: "2026-06-05",
    impact: "high",
    context: "Turborepo excellent for JS/TS but team adding Golang and Python services. Need cross-language task orchestration.",
    decision: "Evaluate Nx for monorepo management with first-class Go and Python support. Proof-of-concept in Q3.",
    consequences: "If adopted, enables unified dependency graph across languages. Migration from Turborepo is non-trivial.",
    supersededBy: null,
  },
];

// ─── 8 Tech Stack Assessments ─────────────────────────────────────────────────

export const demoTechAssessments: TechStackAssessment[] = [
  {
    id: "tsa-001",
    category: "frontend",
    technology: "Next.js 15 + React 19",
    version: "15.4.6",
    verdict: "adopt",
    rationale: "App Router stable, server components mature, excellent SSR performance. Team proficiency high after 6 months.",
    lastEvaluated: "2026-05-01",
    migrationCost: "none",
    teamProficiency: 88,
  },
  {
    id: "tsa-002",
    category: "backend",
    technology: "Go 1.23",
    version: "1.23.4",
    verdict: "trial",
    rationale: "Strong performance for data-intensive services. Growing team interest. Existing Node.js services sufficient for most workloads.",
    lastEvaluated: "2026-04-15",
    migrationCost: "high",
    teamProficiency: 42,
  },
  {
    id: "tsa-003",
    category: "data",
    technology: "PostgreSQL 16 + Supabase",
    version: "16.4",
    verdict: "adopt",
    rationale: "Production-proven with row-level security. Managed hosting reduces DBA burden. JSONB covers document use cases.",
    lastEvaluated: "2026-03-20",
    migrationCost: "low",
    teamProficiency: 79,
  },
  {
    id: "tsa-004",
    category: "infrastructure",
    technology: "Kubernetes (EKS)",
    version: "1.31",
    verdict: "adopt",
    rationale: "Mature orchestration. Team has 2 years of operational experience. Cost optimization with spot instances in place.",
    lastEvaluated: "2026-02-28",
    migrationCost: "none",
    teamProficiency: 76,
  },
  {
    id: "tsa-005",
    category: "devops",
    technology: "Terraform + Atlantis",
    version: "1.10",
    verdict: "adopt",
    rationale: "Infrastructure-as-code mandatory for SOC 2. Atlantis provides PR-based plan/apply workflow.",
    lastEvaluated: "2026-05-15",
    migrationCost: "none",
    teamProficiency: 72,
  },
  {
    id: "tsa-006",
    category: "security",
    technology: "Snyk + Dependabot",
    version: "latest",
    verdict: "adopt",
    rationale: "Automated vulnerability scanning integrated into CI. Low false-positive rate. SOC 2 requirement satisfied.",
    lastEvaluated: "2026-03-01",
    migrationCost: "low",
    teamProficiency: 85,
  },
  {
    id: "tsa-007",
    category: "mobile",
    technology: "React Native + Expo",
    version: "0.76",
    verdict: "assess",
    rationale: "Business case for mobile app emerging. Team has React expertise but no native mobile experience. Evaluate vs Flutter.",
    lastEvaluated: "2026-06-01",
    migrationCost: "high",
    teamProficiency: 30,
  },
  {
    id: "tsa-008",
    category: "ai_ml",
    technology: "OpenAI API + LangChain",
    version: "GPT-4o",
    verdict: "trial",
    rationale: "Customer support chatbot pilot shows 40% deflection rate. Cost and latency need monitoring before production commitment.",
    lastEvaluated: "2026-05-30",
    migrationCost: "medium",
    teamProficiency: 55,
  },
];

// ─── Roadmap (6 quarters) ─────────────────────────────────────────────────────

export const demoRoadmap: RoadmapItem[] = [
  {
    id: "rm-001",
    quarter: "Q2 2026",
    initiative: "Platform authentication overhaul (OAuth 2.1 + passkeys)",
    phase: "build",
    progress: 65,
    owner: "Sarah Chen",
    dependencies: [],
    riskLevel: "medium",
  },
  {
    id: "rm-002",
    quarter: "Q2 2026",
    initiative: "CI/CD pipeline migration to GitHub Actions",
    phase: "launch",
    progress: 90,
    owner: "DevOps Team",
    dependencies: ["ADR-004"],
    riskLevel: "low",
  },
  {
    id: "rm-003",
    quarter: "Q3 2026",
    initiative: "Event-driven order processing (RabbitMQ)",
    phase: "design",
    progress: 20,
    owner: "Marcus Webb",
    dependencies: ["ADR-003"],
    riskLevel: "high",
  },
  {
    id: "rm-004",
    quarter: "Q3 2026",
    initiative: "OpenTelemetry observability rollout",
    phase: "discovery",
    progress: 10,
    owner: "Priya Nair",
    dependencies: ["ADR-007"],
    riskLevel: "medium",
  },
  {
    id: "rm-005",
    quarter: "Q4 2026",
    initiative: "Customer-facing mobile app MVP",
    phase: "discovery",
    progress: 5,
    owner: "Mobile Team",
    dependencies: ["tsa-007"],
    riskLevel: "high",
  },
  {
    id: "rm-006",
    quarter: "Q4 2026",
    initiative: "AI chatbot production deployment",
    phase: "build",
    progress: 35,
    owner: "AI Team",
    dependencies: ["tsa-008"],
    riskLevel: "medium",
  },
  {
    id: "rm-007",
    quarter: "Q1 2027",
    initiative: "Multi-region deployment (EU data residency)",
    phase: "design",
    progress: 5,
    owner: "Infra Team",
    dependencies: ["rm-004"],
    riskLevel: "medium",
  },
  {
    id: "rm-008",
    quarter: "Q1 2027",
    initiative: "Polyglot monorepo migration (Nx)",
    phase: "discovery",
    progress: 0,
    owner: "Platform Team",
    dependencies: ["ADR-012"],
    riskLevel: "high",
  },
  {
    id: "rm-009",
    quarter: "Q2 2027",
    initiative: "Go backend service extraction",
    phase: "discovery",
    progress: 0,
    owner: "Backend Team",
    dependencies: ["tsa-002", "rm-008"],
    riskLevel: "medium",
  },
  {
    id: "rm-010",
    quarter: "Q2 2027",
    initiative: "SOC 2 Type II audit preparation",
    phase: "build",
    progress: 40,
    owner: "CISO Office",
    dependencies: ["rm-004", "tsa-006"],
    riskLevel: "low",
  },
];

// ─── Team Health Metrics ──────────────────────────────────────────────────────

export const demoTeamHealth: TeamHealthMetric[] = [
  {
    id: "th-001",
    name: "Sprint Velocity",
    value: 142,
    unit: "story pts",
    trend: "up",
    changePercent: 8.4,
    benchmark: 130,
    description: "Average story points completed per 2-week sprint across all engineering teams",
  },
  {
    id: "th-002",
    name: "Cycle Time",
    value: 3.8,
    unit: "days",
    trend: "down",
    changePercent: -12.5,
    benchmark: 5.0,
    description: "Median time from first commit to production deploy (lower is better)",
  },
  {
    id: "th-003",
    name: "Code Review Turnaround",
    value: 4.2,
    unit: "hours",
    trend: "up",
    changePercent: 15.3,
    benchmark: 6.0,
    description: "Median time from PR open to first review (lower is better — increasing is a warning)",
  },
  {
    id: "th-004",
    name: "Change Failure Rate",
    value: 4.7,
    unit: "%",
    trend: "down",
    changePercent: -22.1,
    benchmark: 10.0,
    description: "Percentage of deployments causing incidents requiring rollback or hotfix",
  },
  {
    id: "th-005",
    name: "Incident MTTR",
    value: 47,
    unit: "min",
    trend: "down",
    changePercent: -18.2,
    benchmark: 60,
    description: "Mean time to resolve production incidents from alert to mitigation",
  },
  {
    id: "th-006",
    name: "Developer Satisfaction",
    value: 8.1,
    unit: "/10",
    trend: "up",
    changePercent: 5.2,
    benchmark: 7.5,
    description: "Quarterly dev satisfaction survey score across engineering org",
  },
  {
    id: "th-007",
    name: "Test Coverage",
    value: 78,
    unit: "%",
    trend: "up",
    changePercent: 4.1,
    benchmark: 80,
    description: "Overall codebase test coverage across all services",
  },
  {
    id: "th-008",
    name: "Onboarding Time",
    value: 21,
    unit: "days",
    trend: "down",
    changePercent: -9.0,
    benchmark: 30,
    description: "Median days until new engineer ships first production change",
  },
];

// ─── Engineering KPIs ─────────────────────────────────────────────────────────

export const demoEngineeringKPIs: EngineeringMetric[] = [
  {
    id: "eng-001",
    name: "Deployment Frequency",
    value: 24,
    unit: "/week",
    target: 30,
    trend: "up",
    history: [14, 16, 18, 20, 22, 24],
    description: "Production deployments per week across all services",
  },
  {
    id: "eng-002",
    name: "Lead Time for Changes",
    value: 28,
    unit: "hours",
    target: 24,
    trend: "down",
    history: [48, 42, 38, 34, 30, 28],
    description: "Median time from commit to production deploy",
  },
  {
    id: "eng-003",
    name: "Incident Count",
    value: 3,
    unit: "/month",
    target: 2,
    trend: "stable",
    history: [5, 4, 4, 3, 3, 3],
    description: "P1 and P2 production incidents per month",
  },
  {
    id: "eng-004",
    name: "Tech Debt Ratio",
    value: 14.2,
    unit: "%",
    target: 10,
    trend: "down",
    history: [21, 19, 17.5, 16, 15, 14.2],
    description: "Percentage of sprint capacity allocated to tech debt remediation",
  },
  {
    id: "eng-005",
    name: "Security Vulnerabilities",
    value: 8,
    unit: "open",
    target: 0,
    trend: "down",
    history: [22, 18, 15, 12, 10, 8],
    description: "Open critical and high severity vulnerabilities across all services",
  },
  {
    id: "eng-006",
    name: "API P99 Latency",
    value: 320,
    unit: "ms",
    target: 250,
    trend: "stable",
    history: [380, 350, 340, 330, 325, 320],
    description: "99th percentile API response time across all endpoints",
  },
];
